import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// isomorphic-git (via readable-stream / sha.js) pulls in these Node builtins,
// which exist on desktop (Electron) but NOT in Obsidian's mobile WebView. They
// ship as browser polyfills, so we bundle them instead of leaving them external
// — otherwise the plugin fails to load on Android/iOS. The matching `Buffer` /
// `process` globals are supplied by polyfills.mjs via `inject`.
const nodePolyfilled = ["buffer", "process"];

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins.filter((b) => !nodePolyfilled.includes(b)),
	],
	inject: ["polyfills.mjs"],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// `global` is a Node-ism some deps reference; map it to the universal object.
	define: {
		"global": "globalThis",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
